name: Async Typecho Blog Crawler

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Typecho blog post URL to crawl'
        required: true
        default: 'https://www.207725.xyz'
      visit_count:
        description: 'Number of simulated visits (1-5)'
        required: false
        default: '1'

jobs:
  crawl-and-notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp beautifulsoup4 python-telegram-bot lxml fake-useragent aiodns
        
    - name: Run Async Typecho crawler
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TARGET_URL: ${{ github.event.inputs.target_url || 'https://www.207725.xyz' }}
        VISIT_COUNT: ${{ github.event.inputs.visit_count || '1' }}
      run: |
        python async_typecho_crawler.py "$TARGET_URL" "$VISIT_COUNT"
        
    - name: Archive results
      uses: actions/upload-artifact@v4  # 这里从v3改为v4
      if: always()
      with:
        name: async-crawl-results
        path: |
          typecho_output.html
          async_crawl_log.txt
