name: Blog Visitor

on:
  schedule:
    # 每天UTC时间0点运行（北京时间8点）
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      visits:
        description: 'Number of visits to simulate'
        required: false
        default: '100'

jobs:
  visit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp asyncio beautifulsoup4
          
      - name: Run blog visitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python blog_visitor.py --visits ${{ github.event.inputs.visits || 100 }}
