name: Typecho Pro Visitor

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分钟运行
  workflow_dispatch:
    inputs:
      normal_visits:
        description: '普通访问次数'
        required: false
        default: '200'
      required_visits:
        description: '每个必刷URL的访问次数'
        required: false
        default: '500'

jobs:
  visit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4
      
      - name: Initialize posts.txt
        run: |
          if [ ! -f posts.txt ]; then
            echo "初始化posts.txt..."
            echo "/index.php/archives/13/" > posts.txt
            echo "/index.php/archives/5/" >> posts.txt
          fi
      
      - name: Run visitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -z "${{ github.event.inputs.required_visits }}" ]; then
            python blog_visitor_pro.py --normal-visits ${{ github.event.inputs.normal_visits || 500 }}
          else
            python blog_visitor_pro.py \
              --normal-visits ${{ github.event.inputs.normal_visits || 11 }} \
              --required-visits ${{ github.event.inputs.required_visits }}
          fi
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visitor-logs
          path: |
            visit.log
            posts.txt
