name: Blog Visitor

on:
  schedule:
    # 每天UTC时间0点运行（北京时间8点）
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      visits:
        description: 'Number of normal visits to simulate (required URLs not included)'
        required: false
        default: '100'

jobs:
  visit:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4
          sudo apt-get update && sudo apt-get install -y python3.11-dev
          
      - name: Ensure posts.txt exists
        run: |
          if [ ! -f posts.txt ]; then
            echo "https://www.207725.xyz/index.php/archives/13/" > posts.txt
            echo "https://www.207725.xyz/index.php/archives/5/" >> posts.txt
            echo "Created default posts.txt with sample URLs"
          else
            echo "Using existing posts.txt"
            cat posts.txt
          fi
          
      - name: Run blog visitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python blog_visitor.py --visits ${{ github.event.inputs.visits || 100 }}
          
      - name: Upload debug files on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visitor-debug-${{ github.run_id }}
          path: |
            *.log
            posts.txt
            blog_visitor.py
