name: Enhanced Typecho Blog Crawler

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      start_page:
        description: 'Start page number to crawl'
        required: false
        default: '1'
      max_pages:
        description: 'Maximum pages to crawl'
        required: false
        default: '1'

jobs:
  crawl-and-notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp beautifulsoup4 python-telegram-bot lxml fake-useragent aiodns tqdm
        
    - name: Run Enhanced Typecho crawler
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        BLOG_URL: 'https://www.207725.xyz'
        START_PAGE: ${{ github.event.inputs.start_page || '1' }}
        MAX_PAGES: ${{ github.event.inputs.max_pages || '1' }}
      run: |
        python enhanced_typecho_crawler.py
        
    - name: Archive results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: typecho-crawl-results
        path: |
          typecho_output/
          crawl_log.txt
