name: Typecho Blog Crawler

on:
  schedule:
    # 每天 UTC 时间 8:00 运行 (北京时间 16:00)
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Typecho blog post URL to crawl'
        required: true
        default: 'https://www.207725.xyz'

jobs:
  crawl-and-notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-telegram-bot lxml
        
    - name: Run Typecho crawler
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TARGET_URL: ${{ github.event.inputs.target_url || 'https://www.207725.xyz' }}
      run: |
        python typecho_crawler.py "$TARGET_URL"
        
    - name: Archive results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: typecho-crawl-results
        path: typecho_output.html
